/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laundryapp;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextArea;

import java.awt.Desktop;
import java.net.URI;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

/**
 *
 * @author danarbonarbuwono
 */
public class DataCustomer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataCustomer.class.getName());

    /**
     * Creates new form DataCustomer
     */
    public DataCustomer() {
        initComponents();
        
        
        tampilData();
    }
    
    private void tampilData() {

    DefaultTableModel model =
        new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("No HP");
    model.addColumn("Tanggal");
    model.addColumn("Paket");
    model.addColumn("Harga");
    model.addColumn("Berat");
    model.addColumn("Total");
    model.addColumn("Estimasi");
    model.addColumn("Maks Ambil");
    model.addColumn("Status Pengambilan");
    model.addColumn("Status Pembayaran");

    try {

        Connection conn =
            Koneksi.getConnection();

        Statement st =
            conn.createStatement();

        ResultSet rs =
            st.executeQuery(
            "SELECT * FROM transaksi ORDER BY id DESC");

        while(rs.next()) {

            model.addRow(new Object[] {
                
                rs.getInt("id"),
                rs.getString("nama_customer"),
                rs.getString("no_hp"),
                rs.getDate("tanggal_masuk"),
                rs.getString("paket"),
                rs.getInt("harga_perkg"),
                rs.getDouble("berat"),
                rs.getDouble("total_biaya"),
                rs.getString("estimasi"),
                rs.getString("maks_pengambilan"),
                rs.getString("status_pengambilan"),
                rs.getString("status_pembayaran")
                    
        });

        }

        tableTransaksi.setModel(model);

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
            this,
            e.getMessage()
        );

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Cetaknota = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        jLabel2.setText("Sari Laundry");

        jLabel1.setFont(new java.awt.Font("Kannada MN", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Customer");

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Customer", "Paket", "Berat", "Total biaya", "Estimasi", "No HP", "Tanggal masuk", "Maks pengambilan", "Status pengambilan", "Status pembayaran"
            }
        ));
        jScrollPane1.setViewportView(tableTransaksi);

        Refresh.setText("Refresh");
        Refresh.addActionListener(this::RefreshActionPerformed);

        Hapus.setText("Hapus");
        Hapus.addActionListener(this::HapusActionPerformed);

        Cetaknota.setText("Cetak nota");
        Cetaknota.addActionListener(this::CetaknotaActionPerformed);

        Kembali.setText("Kembali");
        Kembali.addActionListener(this::KembaliActionPerformed);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Cari Nota");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Ubah Status Pembayaran");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Ubah Status Pengambilan");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cetaknota, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cetaknota)
                    .addComponent(Hapus)
                    .addComponent(Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(Kembali)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
  
    new MenuUtama().setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_KembaliActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
    
        tampilData();

        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed

    int baris = tableTransaksi.getSelectedRow();

    if(baris == -1){
        JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu!");
        return;
    }

    String id = tableTransaksi.getValueAt(baris,0).toString();

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if(konfirmasi == JOptionPane.YES_OPTION){

        try{
            Connection conn = Koneksi.getConnection();

            String sql =
                    "DELETE FROM transaksi WHERE id=?";

            PreparedStatement pst =
                    conn.prepareStatement(sql);

            pst.setString(1,id);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Data berhasil dihapus");

            tampilData();

        }
        
        catch(Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_HapusActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CetaknotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetaknotaActionPerformed

    int baris = tableTransaksi.getSelectedRow();

    if(baris == -1){
        JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu!");
        return;
    }
    
    String id = tableTransaksi.getValueAt(baris, 0).toString();
    String nama = tableTransaksi.getValueAt(baris, 1).toString();
    String hp = tableTransaksi.getValueAt(baris, 2).toString();
    String tanggal = tableTransaksi.getValueAt(baris, 3).toString();
    String paket = tableTransaksi.getValueAt(baris, 4).toString();
    String harga = tableTransaksi.getValueAt(baris, 5).toString();
    String berat = tableTransaksi.getValueAt(baris, 6).toString();
    String total = tableTransaksi.getValueAt(baris, 7).toString();
    String estimasi = tableTransaksi.getValueAt(baris, 8).toString();
    String maksAmbil = tableTransaksi.getValueAt(baris, 9).toString();
    String statusPengambilan = tableTransaksi.getValueAt(baris, 10).toString();
    String statusPembayaran = tableTransaksi.getValueAt(baris, 11).toString();
    
    String noNota = "NT-" + System.currentTimeMillis();

    String nota =
        "==============================\n" +
        "         SARI LAUNDRY         \n" +
        "==============================\n\n" +

        "No Nota : " + noNota + "\n\n" +

        "Data Customer\n" +
        "------------------------------\n" +
        "Nama    : " + nama + "\n" +
        "No HP   : " + hp + "\n" +
        "Tanggal : " + tanggal + "\n\n" +

        "Paket Laundry\n" +
        "------------------------------\n" +
        "Paket   : " + paket + "\n" +
        "Harga   : Rp." + harga + "\n" +
        "Berat   : " + berat + " Kg\n\n" +

        "Perhitungan\n" +
        "------------------------------\n" +
        "Total   : Rp." + total + "\n" +
        "Estimasi: " + estimasi + "\n\n" +

        "Informasi Pengambilan\n" +
        "------------------------------\n" +
        "Maks Ambil : " + maksAmbil + "\n" +
        "Status Ambil : " + statusPengambilan + "\n" +
        "Status Bayar : " + statusPembayaran + "\n\n" +

        "==============================\n" +
        "      TERIMA KASIH KAK :)     \n" +
        "==============================";
    
    Object[] options = {"Kirim WA", "Tutup"};

    int pilihan = JOptionPane.showOptionDialog(
            this,
            nota,
            "Nota Laundry",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]);

    if (pilihan == 0) {

        try {

            String nomorWA = hp;

            if (nomorWA.startsWith("0")) {
                nomorWA = "62" + nomorWA.substring(1);
            }

            String pesan = URLEncoder.encode(
                    nota,
                    StandardCharsets.UTF_8);

            String url =
                    "https://wa.me/" +
                    nomorWA +
                    "?text=" +
                    pesan;

            Desktop.getDesktop().browse(
                    new URI(url));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Gagal membuka WhatsApp!\n" +
                    e.getMessage());

       }
    
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_CetaknotaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int baris = tableTransaksi.getSelectedRow();

    if(baris == -1){

        JOptionPane.showMessageDialog(
                this,
                "Pilih data terlebih dahulu!");

        return;
    }

    String id =
            tableTransaksi.getValueAt(
                    baris, 0).toString();

    String[] pilihan = {
        "Belum Diambil",
        "Sudah Diambil"
    };

    String statusBaru =
            (String) JOptionPane.showInputDialog(
                    this,
                    "Pilih Status Pengambilan",
                    "Ubah Status Pengambilan",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    pilihan,
                    pilihan[0]);

    if(statusBaru == null){
        return;
    }

    try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
                "UPDATE transaksi "
                + "SET status_pengambilan=? "
                + "WHERE id=?";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1, statusBaru);
        pst.setString(2, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Status pengambilan berhasil diperbarui");

        tampilData();

    }

    catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());

    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    int baris = tableTransaksi.getSelectedRow();

    if(baris == -1){

        JOptionPane.showMessageDialog(
                this,
                "Pilih data terlebih dahulu!");

        return;
    }

    String id =
            tableTransaksi.getValueAt(
                    baris, 0).toString();

    String[] pilihan = {
        "Belum Lunas",
        "Lunas"
    };

    String statusBaru =
            (String) JOptionPane.showInputDialog(
                    this,
                    "Pilih Status Pembayaran",
                    "Ubah Status",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    pilihan,
                    pilihan[0]);

    if(statusBaru == null){
        return;
    }

    try {

        Connection conn =
                Koneksi.getConnection();

        String sql =
                "UPDATE transaksi "
                + "SET status_pembayaran=? "
                + "WHERE id=?";

        PreparedStatement pst =
                conn.prepareStatement(sql);

        pst.setString(1, statusBaru);
        pst.setString(2, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Status pembayaran berhasil diperbarui");

        tampilData();

    }

    catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());

    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetaknota;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
