/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laundryapp;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;

/**
 *
 * @author danarbonarbuwono
 */
public class FormPemasukan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPemasukan.class.getName());

    /**
     * Creates new form FormPemasukan
     */
    public FormPemasukan() {
        initComponents();
        tampilData();
    }

    private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("Tanggal");
    model.addColumn("Paket");
    model.addColumn("Total");
    model.addColumn("Status Pembayaran");

    double totalHarian = 0;
    double totalMingguan = 0;
    double totalBulanan = 0;

    LocalDate hariIni = LocalDate.now();

    try {

        Connection conn = Koneksi.getConnection();

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery(
            "SELECT tanggal_masuk,paket,total_biaya,status_pembayaran " +
            "FROM transaksi " +
            "WHERE status_pembayaran='Lunas'"
        );

        while(rs.next()) {
            
            

            LocalDate tanggal =
                rs.getDate("tanggal_masuk").toLocalDate();

            double total =
                rs.getDouble("total_biaya");

            model.addRow(new Object[] {

                tanggal,
                rs.getString("paket"),
                total,
                rs.getString("status_pembayaran")

            });

            // Total Hari Ini
            if(tanggal.equals(hariIni)) {

                totalHarian += total;

            }

            // Total Minggu Ini
            if(!tanggal.isBefore(hariIni.minusDays(7))) {

                totalMingguan += total;

            }

            // Total Bulan Ini
            if(tanggal.getMonthValue() ==
                    hariIni.getMonthValue()
                    &&
               tanggal.getYear() ==
                    hariIni.getYear()) {

                totalBulanan += total;

            }

        }

        tablePemasukan.setModel(model);
        
        System.out.println("Harian = " + totalHarian);
        System.out.println("Mingguan = " + totalMingguan);
        System.out.println("Bulanan = " + totalBulanan);

        lblHarian.setText(
                "Total Hari Ini : Rp " + totalHarian);

        lblMingguan.setText(
                "Total Minggu Ini : Rp " + totalMingguan);

        lblBulanan.setText(
                "Total Bulan Ini : Rp " + totalBulanan);

    }

    catch(Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePemasukan = new javax.swing.JTable();
        lblHarian = new javax.swing.JLabel();
        lblMingguan = new javax.swing.JLabel();
        lblBulanan = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Paket", "Total", "Status Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(tablePemasukan);

        lblHarian.setText("Total Hari Ini :");

        lblMingguan.setText("Total Minggu Ini :");

        lblBulanan.setText("Total Bulan Ini :");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(49, 49, 49)
                        .addComponent(btnKembali))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMingguan, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(lblBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarian)
                    .addComponent(lblBulanan))
                .addGap(52, 52, 52)
                .addComponent(lblMingguan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnRefresh))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

    tampilData();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
      
    MenuUtama menu = new MenuUtama();
    menu.setVisible(true);

    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPemasukan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBulanan;
    private javax.swing.JLabel lblHarian;
    private javax.swing.JLabel lblMingguan;
    private javax.swing.JTable tablePemasukan;
    // End of variables declaration//GEN-END:variables
}
